// Common models, including older vehicles. Manual entries cover cars outside
// this starter catalog; this is not a live vehicle identification service.
export const CAR_MODELS = {
  "Alfa Romeo": ["147", "156", "159", "Giulietta", "Giulia", "MiTo", "Stelvio", "Tonale"],
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "TT"],
  "BMW": ["Série 1", "Série 2", "Série 3", "Série 4", "Série 5", "Série 6", "Série 7", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "i3", "i4", "iX"],
  "Citroën": ["C1", "C2", "C3", "C3 Aircross", "C3 Picasso", "C4", "C4 Cactus", "C4 Picasso", "Grand C4 Picasso", "C4 SpaceTourer", "C5", "C5 Aircross", "C5 X", "Berlingo", "Saxo", "Xsara", "Xsara Picasso"],
  "Dacia": ["Sandero", "Logan", "Duster", "Jogger", "Spring", "Lodgy", "Dokker"],
  "DS": ["DS 3", "DS 3 Crossback", "DS 4", "DS 5", "DS 7", "DS 7 Crossback", "DS 9"],
  "Fiat": ["500", "500X", "500L", "Panda", "Punto", "Grande Punto", "Tipo", "Bravo", "Doblo", "Qubo"],
  "Ford": ["Fiesta", "Focus", "Puma", "Kuga", "Mondeo", "Ka", "Ka+", "EcoSport", "S-Max", "C-Max", "Galaxy", "Mustang", "Mustang Mach-E"],
  "Honda": ["Civic", "Jazz", "Accord", "CR-V", "HR-V", "e"],
  "Hyundai": ["i10", "i20", "i30", "i40", "Kona", "Tucson", "Santa Fe", "Ioniq", "Ioniq 5", "Ioniq 6"],
  "Jaguar": ["XE", "XF", "XJ", "F-Pace", "E-Pace", "I-Pace", "F-Type"],
  "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Avenger"],
  "Kia": ["Picanto", "Rio", "Ceed", "ProCeed", "XCeed", "Stonic", "Niro", "Sportage", "Sorento", "Soul", "EV6", "EV9"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Sport", "Range Rover Evoque", "Range Rover Velar"],
  "Lexus": ["CT", "IS", "ES", "GS", "LS", "UX", "NX", "RX", "RZ"],
  "Mazda": ["Mazda2", "Mazda3", "Mazda5", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5", "MX-30"],
  "Mercedes-Benz": ["Classe A", "Classe B", "Classe C", "Classe E", "Classe S", "CLA", "CLS", "GLA", "GLB", "GLC", "GLE", "GLS", "EQA", "EQB", "EQC", "EQE", "EQS", "Vito", "Classe V"],
  "MINI": ["Mini", "Cooper", "Clubman", "Countryman", "Cabrio", "Paceman"],
  "Mitsubishi": ["Colt", "Space Star", "ASX", "Eclipse Cross", "Outlander", "Pajero"],
  "Nissan": ["Micra", "Note", "Juke", "Qashqai", "X-Trail", "Pulsar", "Leaf", "Ariya"],
  "Opel": ["Adam", "Karl", "Corsa", "Astra", "Insignia", "Meriva", "Zafira", "Mokka", "Crossland", "Grandland", "Combo"],
  "Peugeot": ["106", "107", "108", "206", "207", "208", "306", "307", "308", "406", "407", "508", "2008", "3008", "4007", "4008", "5008", "Partner", "Rifter", "RCZ"],
  "Porsche": ["911", "Boxster", "Cayman", "718", "Cayenne", "Macan", "Panamera", "Taycan"],
  "Renault": ["Twingo", "Clio", "Captur", "Mégane", "Scénic", "Grand Scénic", "Kadjar", "Koleos", "Austral", "Arkana", "Espace", "Laguna", "Talisman", "Zoé", "Kangoo", "Modus"],
  "SEAT": ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Alhambra", "Altea", "Mii", "Toledo"],
  "Škoda": ["Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq", "Citigo", "Yeti", "Rapid"],
  "Smart": ["Fortwo", "Forfour", "#1", "#3"],
  "Suzuki": ["Swift", "Ignis", "Baleno", "Vitara", "S-Cross", "Jimny", "Splash", "Swace", "Across"],
  "Tesla": ["Model 3", "Model Y", "Model S", "Model X"],
  "Toyota": ["Aygo", "Aygo X", "Yaris", "Yaris Cross", "Corolla", "Auris", "C-HR", "RAV4", "Prius", "Avensis", "Verso", "Land Cruiser", "bZ4X"],
  "Volkswagen": ["Polo", "Golf", "Passat", "T-Roc", "T-Cross", "Taigo", "Tiguan", "Touareg", "Touran", "Sharan", "up!", "ID.3", "ID.4", "ID.5", "ID.7", "Arteon", "Caddy", "New Beetle"],
  "Volvo": ["C30", "V40", "V60", "V70", "V90", "S40", "S60", "S80", "S90", "XC40", "XC60", "XC90", "EX30", "EX90"],
};

export const CAR_BRANDS = Object.keys(CAR_MODELS).sort((a, b) => a.localeCompare(b, "fr"));